/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.tabela.verdade;

/**
 *
 * @author vitor.saldanha
 */
public class welcome extends javax.swing.JFrame {

    private String nome;

    /**
     * Creates new form QuizTabelasVerdade
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertName = new javax.swing.JTextField();
        Info = new javax.swing.JLabel();
        Enter = new javax.swing.JButton();
        Info1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz");
        setBackground(new java.awt.Color(241, 223, 223));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().setLayout(null);

        insertName.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        insertName.setText("Insert name here");
        insertName.setCaretColor(new java.awt.Color(204, 204, 204));
        insertName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNameActionPerformed(evt);
            }
        });
        getContentPane().add(insertName);
        insertName.setBounds(10, 180, 340, 45);

        Info.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        Info.setText("Bem-vindo ao Quiz sobre portas lógicas!");
        getContentPane().add(Info);
        Info.setBounds(10, 80, 369, 71);

        Enter.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        Enter.setText("Entrar");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        getContentPane().add(Enter);
        Enter.setBounds(10, 230, 90, 34);

        Info1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        Info1.setText("Para começarmos, insira seu nome");
        getContentPane().add(Info1);
        Info1.setBounds(10, 130, 369, 71);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vitor.saldanha\\Desktop\\question_quiz_mark_bubble_ask_qa-512.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 30, 460, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertNameActionPerformed
        this.nome = this.insertName.getText();
    }//GEN-LAST:event_insertNameActionPerformed

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        //botao de ação 


    }//GEN-LAST:event_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });

        new welcome().setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Info1;
    private javax.swing.JTextField insertName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nome
     */
    public String getNome() {
        return nome;
    }

    /**
     * @param nome the nome to set
     */
    public void setNome(String nome) {
        this.nome = nome;
    }
}
