/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor.saldanha
 */
public class exercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form exercicio1
     */
    public exercicio2() {
        initComponents();
        setTitle("Exercicio 2");        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }
    boolean correctResponse = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        label_question2 = new javax.swing.JLabel();
        img_orCircuit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        label_ex2 = new javax.swing.JLabel();
        img_xor = new javax.swing.JLabel();
        alternativa_a = new javax.swing.JRadioButton();
        alternativa_b = new javax.swing.JRadioButton();
        img_and = new javax.swing.JLabel();
        img_not = new javax.swing.JLabel();
        alternativa_d = new javax.swing.JRadioButton();
        img_andnot = new javax.swing.JLabel();
        alternativa_c = new javax.swing.JRadioButton();
        envia_resposta = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jButton1.setText("Enviar resposta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        label_question2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        label_question2.setText("Então você conseguiu... Quero ver acertar essa: Mesmo esquema!");

        img_orCircuit.setIcon(new javax.swing.ImageIcon("C:\\Users\\vitor.saldanha\\Documents\\NetBeansProjects\\ProjetoIntegrador\\Saved Pictures\\circuit_or.png")); // NOI18N
        img_orCircuit.setText("jLabel2");

        jRadioButton2.setText("jRadioButton1");

        label_ex2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        label_ex2.setText("EXERCICIO 2:");

        img_xor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jframes/images/or.png"))); // NOI18N
        img_xor.setText("jLabel8");

        buttonGroup1.add(alternativa_a);
        alternativa_a.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        alternativa_a.setText("A)");
        alternativa_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa_aActionPerformed(evt);
            }
        });

        buttonGroup1.add(alternativa_b);
        alternativa_b.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        alternativa_b.setText("B)");
        alternativa_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa_bActionPerformed(evt);
            }
        });

        img_and.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jframes/images/and.png"))); // NOI18N
        img_and.setText("jLabel8");

        img_not.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jframes/images/not.png"))); // NOI18N
        img_not.setText("jLabel8");

        buttonGroup1.add(alternativa_d);
        alternativa_d.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        alternativa_d.setText("D)");
        alternativa_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa_dActionPerformed(evt);
            }
        });

        img_andnot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jframes/images/and-not.png"))); // NOI18N
        img_andnot.setText("jLabel8");

        buttonGroup1.add(alternativa_c);
        alternativa_c.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        alternativa_c.setText("C)");
        alternativa_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa_cActionPerformed(evt);
            }
        });

        envia_resposta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        envia_resposta.setText("Enviar resposta");
        envia_resposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envia_respostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(img_orCircuit, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alternativa_c, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alternativa_a))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_and, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(alternativa_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_andnot, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alternativa_d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(img_not, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_question2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(envia_resposta)
                        .addGap(335, 335, 335))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(343, 343, 343)
                    .addComponent(jRadioButton2)
                    .addContainerGap(469, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(label_ex2)
                    .addContainerGap(710, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label_question2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_orCircuit, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(img_xor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alternativa_a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alternativa_b)
                                    .addComponent(img_andnot, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(img_and, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(img_not, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alternativa_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(alternativa_c, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)))
                .addComponent(envia_resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(422, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(342, 342, 342)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(label_ex2)
                    .addContainerGap(720, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternativa_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa_aActionPerformed
        correctResponse = true;

    }//GEN-LAST:event_alternativa_aActionPerformed

    private void alternativa_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa_bActionPerformed
        correctResponse = false;
    }//GEN-LAST:event_alternativa_bActionPerformed

    private void alternativa_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa_dActionPerformed
        correctResponse = false;
    }//GEN-LAST:event_alternativa_dActionPerformed

    private void alternativa_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa_cActionPerformed
        correctResponse = false;
    }//GEN-LAST:event_alternativa_cActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        correctResponse = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void envia_respostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envia_respostaActionPerformed
        if (correctResponse) {
            JOptionPane.showMessageDialog(null, "Muito bem, está correto!");
            exercicio3 ex3_screen = new exercicio3();
            ex3_screen.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Resposta errada meu amigo!");
        }

    }//GEN-LAST:event_envia_respostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alternativa_a;
    private javax.swing.JRadioButton alternativa_b;
    private javax.swing.JRadioButton alternativa_c;
    private javax.swing.JRadioButton alternativa_d;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton envia_resposta;
    private javax.swing.JLabel img_and;
    private javax.swing.JLabel img_andnot;
    private javax.swing.JLabel img_not;
    private javax.swing.JLabel img_orCircuit;
    private javax.swing.JLabel img_xor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel label_ex2;
    private javax.swing.JLabel label_question2;
    // End of variables declaration//GEN-END:variables
}
